-- Realized that the BIGSERIAL type automatically creates a sequence but BIGINT does not
-- Also realized that BIGSERIAL isn't a type, it's a column identity
-- BIGSERIAL = BIGINT plus an automatically created sequence
-- We can't change the BIGINT type, so we just use GENERATED BY DEFAULT AS IDENTITY to effectively make it BIGSERIAL

ALTER TABLE orders ALTER COLUMN id 
	ADD GENERATED BY DEFAULT AS IDENTITY; 

ALTER TABLE users ALTER COLUMN id 
	ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE product ALTER COLUMN id 
	ADD GENERATED BY DEFAULT AS IDENTITY;    

ALTER TABLE product_order ALTER COLUMN id 
	ADD GENERATED BY DEFAULT AS IDENTITY;